export const GET_CHANNELS = 'GET_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const RENAME_CHANNEL = 'RENAME_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
