export const GET_CHANNELS = 'GET_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const RENAME_CHANNEL = 'RENAME_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';
export const SET_CURRENT_CHANNEL_ID = 'SET_CURRENT_CHANNEL_ID';
export const ADD_MESSAGE_REQUEST = 'ADD_MESSAGE_REQUEST';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';
