export const ADD_CHANNEL_REQUEST = 'ADD_CHANNEL_REQUEST';
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_FAILURE = 'ADD_CHANNEL_FAILURE';

export const RENAME_CHANNEL_REQUEST = 'RENAME_CHANNEL_REQUEST';
export const RENAME_CHANNEL_SUCCESS = 'RENAME_CHANNEL_SUCCESS';
export const RENAME_CHANNEL_FAILURE = 'RENAME_CHANNEL_FAILURE';

export const REMOVE_CHANNEL_REQUEST = 'REMOVE_CHANNEL_REQUEST';
export const REMOVE_CHANNEL_SUCCESS = 'REMOVE_CHANNEL_SUCCESS';
export const REMOVE_CHANNEL_FAILURE = 'REMOVE_CHANNEL_FAILURE';

export const SET_CURRENT_CHANNEL_ID = 'SET_CURRENT_CHANNEL_ID';

export const ADD_MESSAGE_REQUEST = 'ADD_MESSAGE_REQUEST';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';
export const REMOVE_CHANNEL_MESSAGES = 'REMOVE_CHANNEL_MESSAGES';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
